export const components = 'components'
export const isProjectsPaneWaiting = 'isProjectsPaneWaiting'
export const projects = 'projects'
export const selectedProjectId = 'selectedProjectId'
export const stateDiagramActions = 'stateDiagramActions'
export const stateDiagramComponents = 'stateDiagramComponents'
export const stateDiagramMutations = 'stateDiagramMutations'
export const stateDiagramStateVariables = 'stateDiagramStateVariables'
