export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const SELECT_PROJECT = 'SELECT_PROJECT'
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS'
